//HintName: AuditRecordBase.g.cs
// <auto-generated />

using System;

namespace OceanWebSystems.Audit.EntityFramework
{
    public abstract class AuditRecordBase : IAuditRecord
    {
        public DateTime AuditDate { get; set; }

        public string AuditAction { get; set; }

        public int? AuditUserId { get; set; }

        public string AuditUserName { get; set; }

        public string AuditUserDisplayName { get; set; }
    }
}
