//HintName: IAudit.g.cs
// <auto-generated />

using System;

namespace OceanWebSystems.Audit.EntityFramework
{
    public interface IAudit
    {
        DateTime AuditDate { get; set; }

        string AuditAction { get; set; }

        int? UserId { get; set; }

        string UserName { get; set; }
    }
}
