//HintName: IAuditRecord.g.cs
// <auto-generated />

using System;

namespace OceanWebSystems.Audit.EntityFramework
{
    public interface IAuditRecord
    {
        DateTime AuditDate { get; set; }

        string AuditAction { get; set; }

        int? AuditUserId { get; set; }

        string AuditUserName { get; set; }

        string AuditUserDisplayName { get; set; }
    }
}
