//HintName: AuditConfigurationAttribute.g.cs
// <auto-generated />

using System;

#nullable enable

namespace OceanWebSystems.Audit.EntityFramework
{
    public class AuditConfigurationAttribute : Attribute
    {
        public AuditConfigurationAttribute(
            string tableNamePrefix = "",
            string tableNameSuffix = "AuditRecord",
            string softDeleteColumnName = "IsDeleted",
            bool softDeleteDeletedValue = true)
        {
            TableNamePrefix = tableNamePrefix;
            TableNameSuffix = tableNameSuffix;
            SoftDeleteColumnName = softDeleteColumnName;
            SoftDeleteDeletedValue = softDeleteDeletedValue;
        }

        public AuditConfigurationAttribute(AuditConfigurationOptions configOptions)
        {
            TableNamePrefix = configOptions.TableNamePrefix;
            TableNameSuffix = configOptions.TableNameSuffix;
            SoftDeleteColumnName = configOptions.SoftDeleteColumnName;
            SoftDeleteDeletedValue = configOptions.SoftDeleteDeletedValue;
        }

        public string? TableNamePrefix { get; }

        public string? TableNameSuffix { get; }

        public string? SoftDeleteColumnName { get; }

        public bool? SoftDeleteDeletedValue { get; }
    }
}
