//HintName: TestDbContext.g.cs
// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore;
using OceanWebSystems.Data.Models;

namespace OceanWebSystems.Data.Context
{
	public partial class TestDbContext
	{
		public virtual DbSet<AuditTestModelAuditRecord> AuditTestModelAuditRecords { get; set; }
	}
}
