//HintName: NoPropertiesAudit.g.cs
// <auto-generated />

using System;
using System.ComponentModel.DataAnnotations;
using OceanWebSystems.Audit.EntityFramework;

namespace OceanWebSystems.Data.Models
{
	public partial class NoPropertiesAudit : AuditBase
	{
		[Key]
		public int AuditId { get; set; }
	}
}
