//HintName: TestModelAuditRecord.g.cs
// <auto-generated />

using System;
using System.ComponentModel.DataAnnotations;
using OceanWebSystems.Audit.EntityFramework;

namespace OceanWebSystems.Data.Models
{
	public partial class TestModelAuditRecord : AuditRecordBase
	{
		[Key]
		public int AuditId { get; set; }

		public int Id { get; set; }
	}
}
