name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./OceanWebSystems.Audit.EntityFramework/
    - name: Build
      run: dotnet build --no-restore ./OceanWebSystems.Audit.EntityFramework/
    - name: Test
      run: dotnet test --no-build --verbosity normal ./OceanWebSystems.Audit.EntityFramework/
    - name: Publish
      uses: rohith/publish-nuget@v2
      with:
          PROJECT_FILE_PATH: ./OceanWebSystems.Audit.EntityFramework/OceanWebSystems.Audit.EntityFramework/OceanWebSystems.Audit.EntityFramework.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
